wordpress:
  # image: wordpress
  image: j8seangel/wp-nocache
  links:
    - db:mysql
  ports:
    - 8080:80
  volumes:
    - ./theme:/var/www/html/wp-content/themes/_s
db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
